### ISSUE TITLE
Mongodb has no arm32v7 image for raspi

### ISSUE THREAD

**Issue by krissrex** [AbaKYS/elo-bot#4]

**Comment by krissrex** [comment]
Use `webhippie/mongodb` instead.

**Comment by krissrex** [comment]
> Use `webhippie/mongodb` instead.

The env options don't work. So manually start the container, `docker exec -it mongo bash`,
run `mongo`, `use admin`, create the user:
```js
db.createUser(
  {
    user: 'admin',
     pwd: 'kys',
     roles: [ { role: 'root', db: 'admin' } ]
   }
 );
```
`exit` 
then `mongo -u admin -p kys` ,
`use elo-rankings`
then lastly
```js
db.createUser({
   user: "elobot",
   pwd: "kys",
   roles: [
     {
       role: "readWrite",
       db: "elo-rankings",
     },
   ],
 });
```

**Comment by krissrex** [comment]
If the db corrupts, e.g. with lockfile remaining, add this to docker-compose and run it once with `docker-compose up mongo-repair`:

```yaml
services:
  mongo-repair:
    image: webhippie/mongodb
    user: "mongodb:mongodb"
    container_name: mongo-repair
    hostname: mongo-repair
    environment:
      MONGODB_DATABASE: elo-rankings
      MONGODB_DBPATH: /data/db
      MONGODB_CONFIG: /etc/mongodb.conf
    command: ["mongod", "--repair"]
    volumes:
      - "./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"
      - "./mongodb:/data/db"
      - "./mongodb.conf:/etc/mongodb.conf"
```

**Comment by krissrex** [comment]
> Use `webhippie/mongodb` instead.

```yaml
version: "3.3"

services:
  mongo:
    image: webhippie/mongodb
    restart: "unless-stopped"
    container_name: mongo
    hostname: mongo
    environment:
      MONGODB_DATABASE: elo-rankings
      MONGODB_DBPATH: /data/db
      MONGODB_CONFIG: /etc/mongodb.conf
    volumes:
      - "./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"  # Not running automatically!
      - "./mongodb:/data/db"
      - "./mongodb.conf:/etc/mongodb.conf"
  elo-bot:
    image: krissrex/discord-elo-bot:arm32v7
    restart: "unless-stopped"
    depends_on:
      - mongo
    links:
      - mongo:mongo
    environment:
      # Modify the values in the .env file
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      MONGO_URI: ${MONGO_URI}
```
